### ISSUE TITLE
random player get discord return 401 UNAUTHORIZED for bot

### ISSUE THREAD

**Issue by SNIPER722** [shibdib/Keepstar#2]
I got some random player auth their character get 

> '''Client error: POST https://discordapp.com/api/oauth2/token resulted in a 401 UNAUTHORIZED response: {"error": "invalid_grant"}'''

I tried re-generate bot secret, reset bot and etc. don't work
picture post on discord: https://cdn.discordapp.com/attachments/389904731088224258/403475565581172747/unknown.png

exception is throw in third party lib.

**Comment by SNIPER722** [comment]
this happen on random player not all the player are affected.

**Comment by shibdib** [comment]
having trouble getting this to duplicate, which is making debugging it an issue.

Do the same people always have this issue or does it work eventually for everyone?

**Comment by SNIPER722** [comment]
same people always have this issue. some people do not meet this at all....

**Comment by nsdonner** [comment]
yep, same problem

**Comment by nsdonner** [comment]
Deleting coockies solves the problem, so i guess it should be fixed by reseting session somewhere in the code.

**Comment by SNIPER722** [comment]
so this will be a problem related to the session. hmmm

**Comment by shibdib** [comment]
session for the site is reset at the start of the process already to avoid issues like this. Possibly this user is having session issues on the discord end?

**Comment by shibdib** [comment]
No further info
