### ISSUE TITLE
Request: Default Auth Role

### ISSUE THREAD

**Issue by epoch18** [shibdib/Keepstar#3]
It would be helpful if I could specify a role name in the coinfig file as the default role that all Discord users would be added to when joining through Keepstar, regardless of whatever corp or alliance they were in. This will allow me to further customize and separate what my authed users and actual corp/alliance members can see. 

Thank you!

**Comment by shibdib** [comment]
This exists, set the id to the default (1234) and it will apply that role to anyone who auths
