### ISSUE TITLE
New Install problem on Ubuntu 20.04

### ISSUE THREAD

**Issue by streitleak** [shibdib/Keepstar#37]
Install failed on Ubuntu 20.04.

Looks its Slim and Twig problem.

first git clone this project and run
`Fatal error: Uncaught Error: Class 'Slim\Slim' not found in /opt/Keepstar/app.php:20 Stack trace: #0 /opt/Keepstar/public/index.php(3): require_once() #1 {main} thrown in /opt/Keepstar/app.php on line 20`
After I google problem. Looks in App.php file is using `new \Slim\Slim()` is wrong. So I changed to `new \Slim\App`.
Looks its working. 

But second problem is coming.
`Fatal error: Uncaught Error: Class 'Slim\View' not found in /opt/Keepstar/vendor/slim/views/Twig.php:45 Stack trace: #0 /opt/Keepstar/vendor/composer/ClassLoader.php(478): include() #1 /opt/Keepstar/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile() #2 [internal function]: Composer\Autoload\ClassLoader->loadClass() #3 /opt/Keepstar/app.php(23): spl_autoload_call() #4 /opt/Keepstar/public/index.php(3): require_once('/opt/Keepstar/a...') #5 {main} thrown in /opt/Keepstar/vendor/slim/views/Twig.php on line 45`
Also I tried to google problem. But not found yet.

**Comment by shibdib** [comment]
I don't even have an active eve account to test/debug this with anymore unfortunately... and every time I debate coming back I look at the changes and say no

**Comment by streitleak** [comment]
It's okay. I am trying to find the way. Just need time. If you have any suggestion, please tell me the possible way to do it. Thanks.

**Comment by streitleak** [comment]
OK... 50% solved.
1. Composer.json 
`{
  "name": `"shibdib/keepstar",
  "description": "Authentication page for Discord and Sluggard",
  "keywords": [
    "authentication",
    "crest",
    "EVE-Online"
  ],
  "license": "MIT",
  "authors": [
    {
      "name": "Bob (Shibdib) Sardinia",
      "homepage": "https://github.com/shibdib"
    },
    {
      "name": "Michael Karbowiak",
      "email": "michael@karbowiak.dk",
      "homepage": "http://karbowiak.dk"
    }
  ],
  "require": {
    "php": ">=5.5.0",
    "ext-mbstring": "*",
    "slim/slim": "^4.9.0",
    "slim/twig-view": "^3.0",
    "zeuxisoo/slim-whoops": "^0.7.0",
    "twig/twig": "^2.0|^3.0",
    "twig/extra-bundle": "^2.0|^3.0",
    "filp/whoops": "^2.0",
    "restcord/restcord": "dev-master",
    "monolog/monolog": "2.3.5",
    "slim/http": "^1.2",
    "slim/psr7": "^1.5"
  }
}
`
    Name changed, 
    remove slim/views
    add slim/twig-view
    add slim/http
    add slim/psr7
2. remove libraries/guzzle folder
3. add // at front of line  `include('guzzle/autoload.php');` in libraries/discord.php  
4. app.php modified to slim 4 with Twig view format.

[app.zip](https://github.com/shibdib/Keepstar/files/7296243/app.zip)

All Tested. Its working fine now.
