### ISSUE TITLE
authentification process

### ISSUE THREAD

**Issue by MyUncleSam** [shibdib/Keepstar#5]
If the user has not connected to the discord server it would be great if the auth step does not end with the discord invite link.

Maybe solutions:
Join the server using Discord API (no idea if this is possible) and continue the auth process.

Show the user something like:
Please connect to the server first before you continue the authentification process:
1. Use this invite code to connect to the discord server: https://discordapp.com/invite/..... (new tab/window)
2. Press continue below (and a continue button somewhere)

**Comment by shibdib** [comment]
I can look into this again, I believe I tried what you're asking but was unable to make it work due to api limitations.

**Comment by shibdib** [comment]
The discord logo if the user receives a "not in server" error is a link to join the server (assuming you put an invite code in the config)
