### ISSUE TITLE
logChannel not working

### ISSUE THREAD

**Issue by MyUncleSam** [shibdib/Keepstar#9]
Hi there,

if I enable the 'logChannel' feature I am no longer able to authenticate. It does not depend on the permissions, I already tried it by giving the bot all groups and admin permissions.

**Exception:**
`GuzzleHttp\Command\Exception\CommandClientException`

**Message:**
`here was an error executing the createMessage command: Client error: 'POST https://discordapp.com/api/v6/channels/<my logChannel id>/messages' resulted in a '400 BAD REQUEST' response:`

**File:**
`Keepstar/app.php`

**Line:**
`350` (but I think it happens in 348 - 351 while using createMessage because if I set logChannel to 0 it is working again)

**Comment by nefalem** [comment]
Hi,

You have to have your bot connect to the websocket gateway at LEAST once before you can create messages. You can do that by opening up <www path>/Keepstar/vendor/restcord/restcord/extra/gateway.html in your browser (any browser).

**Comment by shibdib** [comment]
Nef is correct, but this shouldn't be an issue if you visit the admin page as described in the wiki install steps. (as it does what he says) 

If this is still an issue feel free to reopen this
